update

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -64,9 +64,14 @@ jobs:
     - name: Get Terraform output
       id: get_output
       run: |
-        INSTANCE_PUBLIC_IP=$(terraform output -raw instance_public_ip | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')
-        echo "INSTANCE_PUBLIC_IP=$INSTANCE_PUBLIC_IP" >> $GITHUB_ENV
-        echo "Terraform output: $INSTANCE_PUBLIC_IP" # 디버깅용 메시지 추가
+        INSTANCE_PUBLIC_IP=$(terraform output -raw instance_public_ip | tr -d '\n' | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}')
+        if [[ -z "$INSTANCE_PUBLIC_IP" ]]; then
+          echo "Failed to extract IP address from Terraform output"
+          exit 1
+        fi
+        echo "INSTANCE_PUBLIC_IP=${INSTANCE_PUBLIC_IP}" >> $GITHUB_ENV
+        echo "instance_public_ip=${INSTANCE_PUBLIC_IP}" >> $GITHUB_OUTPUT
+        echo "Terraform output (IP address): ${INSTANCE_PUBLIC_IP}"
 
   deploy:
     needs: terraform
